query getRecipeById($id:String!) {
  getRecipeById(id:$id) {
    id
    pageName
    pageTitle
    url
    text
    createdAt
    updatedAt
    isPublish
    recipeCategoryId
    keywords
    description
    previewId
    previewAlt
    previewTitle
    activeCookingTime
    totalCookingTime
    ingredients {
      id
      ingredientId
      value
      note
    }
  }
}